# create graph of carrels and subject terms
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX terms: <http://purl.org/dc/terms#>
PREFIX crl:   <https://distantreader.org/carrel#>

# denote a graph as output
CONSTRUCT { ?carrel crl:about ?label }

# search
WHERE {
 	
	# get all carrels, their qnumber, and finally, their label
	?carrel  a             crl:carrel .
	?carrel  terms:subject ?qnumber   .
	?qnumber rdfs:label    ?label     .
	
}
