
# given a list of study carrels, count & tabulate subject terms

prefix carrel: <https://distantreader.org/carrel#>
prefix terms:  <http://purl.org/dc/terms#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>

select ?label (count( ?label ) as ?c )
where {
	?s       a             carrel:carrel .
  	?s       terms:subject ?subject      .
  	?subject rdfs:label    ?label        .
}
group by ?label order by desc( ?c )
