
# given a subject term (label), output a list of authors, titles, and urls of carrel items

PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix terms: <http://purl.org/dc/terms#>
prefix crl:   <https://distantreader.org/carrel#>

select ?author ?title ?url
where
{
  ?s       terms:hasPart ?o       .
  ?o       terms:creator ?author  . 
  ?o       terms:title   ?title   .
  ?o       crl:hasCache  ?url     .
  ?o       terms:subject ?qnumber .
  ?qnumber rdfs:label    'woman'  .
}
